version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    volumes:
      - ./data/kafka:/var/run/docker.sock
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    networks:
      - db-network
    volumes:
      - ./data/mongo:/data/db
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  producer:
    container_name: producer
    build: ./producer
    ports:
      - 8080:8080
    volumes:
      - ./producer:/app
    environment:
      - PORT=8080
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/postgres
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=topic1
    depends_on:
      - postgres
      - kafka
  consumer:
    container_name: consumer
    build: ./consumer
    ports:
      - 8081:8080
    networks:
      - db-network
    volumes:
      - ./consumer:/app
    environment:
      - PORT=8081
      - MONGO_URL=mongodb://mongo:27017/consumer?directConnection=true
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=topic1
    depends_on:
      - postgres
      - kafka
networks:
  db-network:
    driver: bridge